#define NIKLIBNAME "nikom.library"
#define NIKRELEASE "v2.5.0"
#define NIKLIBVERSION 26
#define NIKLIBREVISION 1
#define NIKLIBVERSIONSTR "26"
#define NIKLIBREVISIONSTR "1"
#define DOSVERSION "$VER: " NIKLIBNAME "_" NIKRELEASE " " NIKLIBVERSIONSTR "." NIKLIBREVISIONSTR " " __AMIGADATE__
