#define NIKLIBNAME "nikom.library"
#define NIKRELEASE "v2.3.0"
#define NIKLIBVERSION 24
#define NIKLIBREVISION 1
#define NIKLIBVERSIONSTR "24"
#define NIKLIBREVISIONSTR "1"
#define DOSVERSION "$VER: " NIKLIBNAME "_" NIKRELEASE " " NIKLIBVERSIONSTR "." NIKLIBREVISIONSTR " " __AMIGADATE__
