#define NIKLIBNAME "nikom.library"
#define NIKRELEASE "v2.3.1dev"
#define NIKLIBVERSION 24
#define NIKLIBREVISION 2
#define NIKLIBVERSIONSTR "24"
#define NIKLIBREVISIONSTR "2"
#define DOSVERSION "$VER: " NIKLIBNAME "_" NIKRELEASE " " NIKLIBVERSIONSTR "." NIKLIBREVISIONSTR " " __AMIGADATE__
